---
title: "Project Logistic Regression"
author: "IST 707 - Group 5"
date: "2020 M04 16"
output: html_document
---

#Import Libraries
```{r}
library(caret)
library(mlbench)
library(MLmetrics)
library(glmnet)
```

#Load the Datasets
```{r}
logit_train <- readRDS(file = "Balanced_TrainR.Rda")
logit_test <- readRDS(file = "Balanced_TestR.Rda")
```

#Train Model - Baseline
```{r}
set.seed(9)
logit_model <- train(IsBadBuy_1 ~., data=logit_train, method='glm')
logit_model
```

#Predict and Evaluate
```{r}
logit_predictions = predict(logit_model, newdata = logit_test)
confusionMatrix(logit_predictions, logit_test$IsBadBuy_1, positive = "1")
```

#Variable Importancee
```{r}
imp_feat <- varImp(logit_model)


Feature_Importance <- imp_feat$importance
write.csv(Feature_Importance, file = "Feature_Importance.csv", row.names = T)
```

#Logistic with Regularization
```{r}
set.seed(9)
glmGrid <-  expand.grid(alpha = c(0.1, 0.3, 0.5, 0.7), lambda = c(0.01,0.05,0.1))

glmnet_reg = train(IsBadBuy_1 ~., data=logit_train, method = "glmnet", trControl =
                     trainControl(method = "cv", number = 3), tuneGrid = glmGrid, metric =
                     "Accuracy")

glmnet_reg
```

#Predict and Evaluate
```{r}
glmnet_reg_predict <- predict(glmnet_reg, newdata = logit_test)
confusionMatrix(glmnet_reg_predict, logit_test$IsBadBuy_1, positive = "1")
```

